### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by walissonaguirra** [walissonaguirra/php-starter#1]
- [ ] add Class base para controller
- [ ] add Class base para models
- [ ] add Class base para views
- [ ] add Class base para Session
- [ ] add Class support para Email
- [ ] add Class support para Csrf
- [ ] add Class support para Password
- [ ] add componente Router
